version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build
      - docker-compose pull cvat_db
      - docker-compose pull cvat_redis
      - docker-compose pull cvat_proxy
      - docker-compose pull serverless
      - docker tag cvat/server:latest 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat:latest
      - docker tag cvat/ui:latest 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_ui:latest 
      - docker tag postgres:10-alpine 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_db:latest
      - docker tag redis:4.0-alpine 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_redis:latest
      - docker tag nginx:stable-alpine 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_proxy:latest
      - docker tag quay.io/nuclio/dashboard:1.4.8-amd64 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_serverless:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat:latest
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_ui:latest
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_db:latest
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_redis:latest
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_proxy:latest
      - docker push 626843494486.dkr.ecr.us-west-2.amazonaws.com/cvat_serverless:latest
      
