version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build
      - docker tag quay.io/nuclio/dashboard:1.4.8-amd64 310808216338.dkr.ecr.us-west-2.amazonaws.com/serverless:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/serverless:latest


