version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build
      - docker-compose pull cvat_db
      - docker-compose pull cvat_redis
      - docker-compose pull cvat_proxy
      - docker-compose pull serverless
      - docker tag cvat/server:latest 310808216338.dkr.ecr.us-west-2.amazonaws.com/cvat:latest
      - docker tag cvat/ui:latest 310808216338.dkr.ecr.us-west-2.amazonaws.com/cvat_ui:latest 
      - docker tag postgres:10-alpine 310808216338.dkr.ecr.us-west-2.amazonaws.com/postgres:10-alpine
      - docker tag redis:4.0-alpine 310808216338.dkr.ecr.us-west-2.amazonaws.com/cvat_redis:4.0-alpine
      - docker tag nginx:stable-alpine 310808216338.dkr.ecr.us-west-2.amazonaws.com/nginx:stable-alpine
      - docker tag quay.io/nuclio/dashboard:1.4.8-amd64 310808216338.dkr.ecr.us-west-2.amazonaws.com/quay.io/nuclio/dashboard:1.4.8-amd64
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/cvat
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/cvat_ui
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/postgres:10-alpine
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/redis:4.0-alpine
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/nginx:stable-alpine
      - docker push 310808216338.dkr.ecr.us-west-2.amazonaws.com/quay.io/nuclio/dashboard:1.4.8-amd64
      
